### ISSUE TITLE
Pangolin_catkin not found

### ISSUE THREAD

**Issue by salahkhan94** [ethz-asl/orb_slam_2_ros#10]
I think the github repo pangolin is down I am unable to access it
fatal: repository 'https://github.com/ethz-asl/pangolin_catkin.git/' not found

**Comment by ZacharyTaylor** [comment]
There was a typo in the wiki which I will fix now. The issue is that pangolin_catkin is not an ethz-asl package but from the rpg group and can be found here https://github.com/uzh-rpg/pangolin_catkin

**Comment by salahkhan94** [comment]
Hi Zac thanks for the prompt reply! 
I am also facing build errors during installation. 

I have ROS kinetic on Ubuntu 16.04 
I simply cloned all the dependencies (catkin_simple, catkinized version of the orb_slam_2 ..etc)  into the src folder of my workspace and built it 
following are the errors I got :
`Errors     << image_undistort:cmake /home/sal/orbslam_ws/logs/image_undistort/build.cmake.000.log
CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "nlopt" with any of
  the following names:

    nloptConfig.cmake
    nlopt-config.cmake

`
`Warnings   << pangolin_catkin:cmake /home/sal/orbslam_ws/logs/pangolin_catkin/build.cmake.000.log
CMake Warning at /home/sal/orbslam_ws/src/pangolin_catkin/CMakeLists.txt:28 (find_package):
  By not providing "FindDepthSense.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "DepthSense", but CMake did not find one.

  Could not find a package configuration file provided by "DepthSense" with
  any of the following names:

    DepthSenseConfig.cmake
    depthsense-config.cmake

  Add the installation prefix of "DepthSense" to CMAKE_PREFIX_PATH or set
  "DepthSense_DIR" to a directory containing one of the above files.  If
  "DepthSense" provides a separate development package or SDK, be sure it has
  been installed.
`
`Warnings   << pangolin_catkin:make /home/sal/orbslam_ws/logs/pangolin_catkin/build.make.000.log                                               
Cloning into 'pangolin_EXTERNAL'...
Note: checking out '8b6a6b706d50d4172eeb6d5827f40b2207483cf0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 8b6a6b7... Move, Resize for OsxWindow
Build type not set (defaults to release)
-DCMAKE_BUILD_TYPE=Debug for debug
CMake Warning:
  Manually-specified variables were not used by the project:

    CPP11_NO_BOOST


`
Thanks again!

**Comment by alexmillane** [comment]
Image undistort depends on nlopt's catkin package:

git@github.com:ethz-asl/nlopt.git

clone and build this in your workspace.

**Comment by salahkhan94** [comment]
Thanks also,  I had to clone ethz-asl/minkindr and eigen_checks among others.  But the build was successful !!!! 
Thanks a Ton!

**Comment by alexmillane** [comment]
Good to hear. No problem and good luck going forward!

**Comment by junzhang2016** [comment]
I solved the problem:

1. sudo apt-get install libnlopt-dev

2. depends on nlopt's catkin package:
git@github.com:ethz-asl/nlopt.git
clone and build this in your workspace.
https://github.com/ethz-asl/nlopt

3. catkin_make 
4. git clone lidar_align
5. catkin_make
6. $ find / -name "NLOPTConfig.cmake"
	~/catkin_ws/main_ws/src/lidar_align/NLOPTConfig.cmake
7. In ~/catkin_ws/main_ws/src/lidar_align/CmakeLists.txt, before "find_package(NLOPT REQUIRED)", add:
	set(NLOPT_DIR ./)
	(because NLOPTConfig.cmake is under  ~/catkin_ws/main_ws/src/lidar_align/NLOPTConfig.cmake)
