### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by lericson** [ethz-asl/orb_slam_2_ros#16]
minkindr

glog_catkin

eigen_catkin 

eigen_checks

minkindr_conversions

gflags_catkin

**Comment by lericson** [comment]
Also `gflags_catkin` requires to `apt-get install autoconf`

**Comment by lericson** [comment]
To be honest it would make a lot of sense to put these in a `.rosinstall`

**Comment by alexmillane** [comment]
Well spotted. I finally added a .rosinstall. Thanks for pointing this out... It took me a while to get to it.

**Comment by alexmillane** [comment]
solved in #17
